# Environment
$TERMINAL = kitty
$BROWSER = firefox
$EDITOR = emacs
$FILEMGR = thunar

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,cz-Hickson-Black
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,cz-Hickson-Black
env = EDITOR,$EDITOR
env = BROWSER,$BROWSER
env = TERMINAL,$TERMINAL
env = FILEMANAGER,$FILEMGR
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = GTK_THEME,darkarch
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
