# Startup
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = dunst
exec-once = ~/.config/hypr/xdg-portal
exec-once = zsh -lc autostart
exec-once = ~/.config/hypr/update-border.sh

exec-once = command -v xsettingsd >/dev/null 2>&1 && xsettingsd
