# Input
input {
    kb_layout = us
    follow_mouse = 2
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
