# Look and feel
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgba(BB86FCE5)
    col.inactive_border = rgba(1A1A1AEE)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 0.95

    blur {
        enabled = true
        size = 3
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }
}

animations {
    enabled = true
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, default, slide
    animation = windowsOut, 1, 3, default, slide
    animation = windowsMove, 1, 3, default
    animation = border, 1, 6, default
    animation = fade, 1, 6, default
    animation = fadeDim, 1, 6, default
    animation = workspaces, 1, 4, default
}
