# Layouts
dwindle {
    preserve_split = true
}

master {
    new_status = master
    mfact = 0.65
    orientation = center
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
    initial_workspace_tracking = 2
}
