#!/bin/bash
packages=(
    hyprland
    pavucontrol
    thunar
    wl-clipboard
    wf-recorder
    swaybg
    grimblast-git
    ffmpegthumbnailer
    tumbler
    thunar-archive-plugin
    kitty
    waybar
    dunst
    hyprpicker-git
    otf-sora
    ttf-nerd-fonts-symbols-common
    otf-firamono-nerd
)
for package in "${packages[@]}"; do
    if ! yay -Q $package > /dev/null 2>&1; then
        echo "Installing $package..."
        yes "" | yay -S --needed $package
    else
        echo "$package is already installed."
    fi
done