#!/bin/bash
set -euo pipefail

stack_file="/tmp/hide_window_pid_stack.txt"

hide_window() {
    pid=$(hyprctl activewindow -j | jq '.pid')
    hyprctl dispatch movetoworkspacesilent 99,pid:"$pid"
    echo "$pid" >> "$stack_file"
}

show_window() {
    pid=$(tail -1 "$stack_file" 2>/dev/null) || exit
    sed -i '$d' "$stack_file" 2>/dev/null || exit
    [ -z "$pid" ] && exit
    current_workspace=$(hyprctl activeworkspace -j | jq '.id')
    hyprctl dispatch movetoworkspacesilent "$current_workspace",pid:"$pid"
}

case "${1:-}" in
    h) hide_window ;;
    s) show_window ;;
esac
