bind r source-file ~/.config/awesome/configs/tmux.conf
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set -g default-terminal 'kitty'
#set-option -g allow-rename off
#set -g automatic-rename on
set -g set-titles on
set -g set-titles-string '#S [#I - #{pane_current_path}] #W'
set -g history-limit 1000
set -g status-position 'bottom'
set -g status-style 'bg=colour240,fg=colour232'
set -g window-status-style 'bg=colour240,fg=colour232,bold'
set -g window-status-format ' [#I] '
set -g window-status-current-style 'bg=colour254,fg=colour232,bold'
set -g window-status-current-format ' [#I - #W] '
set -g pane-border-style 'fg=colour232'
set -g pane-active-border-style 'bg=colour240,fg=colour232'
set -g status-interval 3
set -g status-left-length 30
set -g status-left '#[fg=colour15,bold] #(whoami) '
set -g status-right '#[bg=colour254,fg=colour232,bold]  %H:%M  #T '
set-option -g message-style 'bg=colour240,fg=colour232'
set-option -g display-panes-active-colour colour232
set-option -g display-panes-colour colour240