PROMPT='%F{#658B5F}%~%F{#c0acd1}❯ %f'
PS1="$PROMPT"
# ArchX zsh config — restored old prompt/source flow, with safe guards.
export PATH="$HOME/.local/share/bin:$HOME/.local/bin:$PATH"
export ZDOTDIR="$HOME/.local/zsh"
export SHELL="$(command -v zsh 2>/dev/null || echo /bin/zsh)"
export HISTFILE="$HOME/.local/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000
mkdir -p "$HOME/.local/zsh" 2>/dev/null || true

if [ -z "${NEOFETCH_RUNNED:-}" ] && [ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ] && command -v neofetch >/dev/null 2>&1; then
    NEOFETCH_RUNNED=1
    export NEOFETCH_RUNNED
    [ "$(pgrep -cx kitty 2>/dev/null || echo 0)" -eq 1 ] && neofetch
fi

CONFSIZE=$(du -sb "$HOME/.local/zsh" 2>/dev/null | awk '{print $1}') # shell config size
command -v thefuck >/dev/null 2>&1 && eval "$(thefuck --alias)"
stty -ixon 2>/dev/null || true

setopt correct
setopt appendhistory
setopt autocd
setopt cdablevars
setopt extended_glob
setopt dotglob
setopt glob_complete

# Completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist 2>/dev/null || true
compinit -d "$HOME/.local/zsh/zcompdump" 2>/dev/null || compinit
_comp_options+=(globdots) ## Include hidden files.
typeset -ga ZSH_AUTOSUGGEST_CLEAR_WIDGETS
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(buffer-empty bracketed-paste accept-line push-line-or-edit)
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Notify
bgnotify_threshold=4
function notify_formatted {
    # $1=exit_status, $2=command, $3=elapsed_time
    local title="Task failed"
    [ "$1" -eq 0 ] && title="Task completed!"
    bgnotify "$title -- after $3 s" "$2" 2>/dev/null || true
}

# Optional tty scrollback helper
if [[ -z ${SSH_TTY:-} ]] && [[ -n ${tty:-} ]]; then
    scroll() {
        if ! command -v scrollback >/dev/null 2>&1; then
            if [ -d "$HOME/.local/share/opt/scrollback/" ]; then
                (cd "$HOME/.local/share/opt/scrollback/" && make && sudo make install)
            fi
        else
            scrollvt='true'
            ! ${SCROLLBACK:-false} false && scrollback -c "$SHELL"
            scrollback "$SHELL"
            unset scrollvt
        fi
    }
fi

# Wal/base16 fzf colors generated by walset. Missing file is okay.
[ -r "$HOME/.cache/wal/colors-fzf.zsh" ] && source "$HOME/.cache/wal/colors-fzf.zsh"
: ${FZF_DEFAULT_OPTS:="--height=40% --layout=reverse --border=rounded --prompt=❯ "}
export FZF_DEFAULT_OPTS

# Old prompt/plugins live here. This restores the original shell feel.
[ -f "$HOME/.local/zsh/Internal/source" ] && source "$HOME/.local/zsh/Internal/source"
