#!/bin/bash
packages=(
    cbatticon
    brightnessctl
    kitty
)
for package in "${packages[@]}"; do
    if ! yay -Q $package > /dev/null 2>&1; then
        echo "Installing $package..."
        yay -S --needed $package
    else
        echo "$package is already installed."
    fi
done