# Generated by walset. Safe for zsh/bash source.
if [ -z "${ARCHX_FZF_COLORS_LOADED:-}" ]; then
  export ARCHX_FZF_COLORS_LOADED=1
  export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --border=rounded --prompt=❯  --pointer=❯ --marker=+ --color=fg:#c0acd1,bg:#0b0b0b,fg+:#c0acd1,bg+:#48534A,hl:#658B5F,hl+:#658B5F,info:#645B97,prompt:#516D55,pointer:#c0acd1,marker:#564F96,spinner:#658B5F,header:#5B5B69,border:#867892,gutter:#0b0b0b ${FZF_DEFAULT_OPTS:-}"
  export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window=down:3:hidden:wrap --bind 'ctrl-/:toggle-preview' ${FZF_CTRL_R_OPTS:-}"
  export FZF_CTRL_T_OPTS="--preview 'fzf-preview {} 2>/dev/null || file -- {}' --preview-window=right:60%:wrap ${FZF_CTRL_T_OPTS:-}"
  export FZF_ALT_C_OPTS="--preview 'ls -la --color=always {} 2>/dev/null | head -80' --preview-window=right:60%:wrap ${FZF_ALT_C_OPTS:-}"
fi
