local appkeys = {}
local command = { column = 3, geometry = { width = 1500, height = 1100 } }
local term = { column = 3, geometry = { width = 1300, height = 300 } }
appkeys["kitty"] = {
    style = term,
    pack = {
        { { "Ctrl" }, "c", nil, { description = "Kill command", group = "Shell" } },
        { { "Ctrl" }, "z", nil, { description = "Suspend command", group = "Shell" } },
        { { "Ctrl" }, "l", nil, { description = "Clears screen", group = "Shell" } },
        { { "Ctrl" }, "f", nil, { description = "Paste selected dir", group = "Shell" } },
        { { "Ctrl" }, "p", nil, { description = "Find text in files", group = "Shell" } },
        { { "Ctrl" }, "r", nil, { description = "Search in history", group = "Shell" } },
        { { "Ctrl" }, "t", nil, { description = "Search in todo", group = "Shell" } },
        { { "Ctrl" }, "b", nil, { description = "Bookmarks", group = "Shell" } },
        { { "alt" }, "c", nil, { description = "Select a dir", group = "Shell" } },
        { { "Ctrl", "Shift" }, "F1", nil, { description = "show help", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "F2", nil, { description = "Edit kitty config", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "F5", nil, { description = "Reload kitty config", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "F6", nil, { description = "Debug kitty config", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "c", nil, { description = "copy", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "v", nil, { description = "paste", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "s", nil, { description = "copy selected", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "o", nil, { description = "Pass selection to program", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "+", nil, { description = "Increase font size", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "-", nil, { description = "Decrease font size", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "Backspace", nil, { description = "Restore font size", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "u", nil, { description = "Input unicode char", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "e", nil, { description = "Open url", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "Delete", nil, { description = "Reset commandinal", group = "Kitty" } },
        { { "Ctrl", "Shift" }, "Escape", nil, { description = "Open kitty shell", group = "Kitty" } },
    }
}
appkeys["tmux"] = {
    style = command,
    pack = {
        { { "Ctrl" , "space" }, "s", nil, { description = "show all sessions", group = "tmux sessions" }},
        { { "Ctrl" , "space" }, "$", nil, { description = "rename the current session", group = "tmux sessions" }},
        { { "Ctrl" , "space" }, "(", nil, { description = "move to previous session", group = "tmux sessions" }},
        { { "Ctrl" , "space" }, ")", nil, { description = "move to next session", group = "tmuspace sessions" }},
        { { "Ctrl" , "space" }, "d", nil, { description = "detach from current session", group = "tmux sessions" }},
        { { "Ctrl" , "space" }, "c", nil, { description = "create window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "f", nil, { description = "find window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, ",", nil, { description = "rename current window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "&", nil, { description = "close current window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "l", nil, { description = "log all windows in a file", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "p", nil, { description = "previous window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "n", nil, { description = "next window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "j", nil, { description = "join window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "s", nil, { description = "send window", group = "tmux windows" }},
        { { "Ctrl" , "space" }, "0...9", nil, { description = "select window by number", group = "tmux windows" }},
        { { "Ctrl" , "space" }, ";", nil, { description = "toggle last active pane", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "%", nil, { description = "split pane vertically", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "\"", nil, { description = "split pane horizontally", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "{", nil, { description = "move the current pane left", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "}", nil, { description = "move the current pane right", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "q 0...9", nil, { description = "select pane by number", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "o", nil, { description = "toggle between panes", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "z", nil, { description = "toggle pane zoom", group = "panes" }},
        { { "Ctrl" , "space" }, "space", nil, { description = "toggle between layouts", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "!", nil, { description = "convert pane into a window", group = "tmux panes" }},
        { { "Ctrl" , "space" }, "x", nil, { description = "close current pane", group = "tmux panes" }},
        { { "Ctrl" , "space" }, ":", nil, { description = "enter command mode", group = "tmux misc" }},
        { { "Ctrl" , "space" }, "?", nil, { description = "list shortcuts", group = "tmux misc" }},
        { { "Ctrl" , "space" }, "t", nil, { description = "show clock", group = "tmux misc" }}
    }
}
appkeys["nvim"] = {
    style = command,
    pack = {
        { {}, "`", nil, { description = "goto mark", group = "nvim motion" }},
        { {}, "0", nil, { description = '"hard" BOL', group = "nvim motion" }},
        { {}, "-", nil, { description = "prev line", group = "nvim motion" }},
        { {}, "w", nil, { description = "next word", group = "nvim motion" }},
        { {}, "e", nil, { description = "end word", group = "nvim motion" }},
        { {}, "[", nil, { description = ". misc", group = "nvim motion" }},
        { {}, "]", nil, { description = ". misc", group = "nvim motion" }},
        { {}, "'", nil, { description = ". goto mk. BOL", group = "nvim motion" }},
        { {}, "b", nil, { description = "prev word", group = "nvim motion" }},
        { {}, "|", nil, { description = "BOL/goto col", group = "nvim motion" }},
        { {}, "$", nil, { description = "EOL", group = "nvim motion" }},
        { {}, "%", nil, { description = "goto matching bracket", group = "nvim motion" }},
        { {}, "^", nil, { description = '"soft" BOL', group = "nvim motion" }},
        { {}, "(", nil, { description = "sentence begin", group = "nvim motion" }},
        { {}, ")", nil, { description = "sentence end", group = "nvim motion" }},
        { {}, "_", nil, { description = '"soft" BOL down', group = "nvim motion" }},
        { {}, "+", nil, { description = "next line", group = "nvim motion" }},
        { {}, "W", nil, { description = "next WORD", group = "nvim motion" }},
        { {}, "E", nil, { description = "end WORD", group = "nvim motion" }},
        { {}, "{", nil, { description = "paragraph begin", group = "nvim motion" }},
        { {}, "}", nil, { description = "paragraph end", group = "nvim motion" }},
        { {}, "G", nil, { description = "EOF/goto line", group = "nvim motion" }},
        { {}, "H", nil, { description = "move cursor to screen top", group = "nvim motion" }},
        { {}, "M", nil, { description = "move cursor to screen middle", group = "nvim motion" }},
        { {}, "L", nil, { description = "move cursor to screen bottom", group = "nvim motion" }},
        { {}, "B", nil, { description = "prev WORD", group = "nvim motion" }},
        { {}, "=", nil, { description = "auto format", group = "nvim operator" }},
        { {}, "y", nil, { description = "yank", group = "nvim operator" }},
        { {}, "d", nil, { description = "delete", group = "nvim operator" }},
        { {}, "~", nil, { description = "toggle case", group = "nvim command" }},
        { {}, "q", nil, { description = ". record macro", group = "nvim command" }},
        { {}, "r", nil, { description = ". replace char", group = "nvim command" }},
        { {}, "i", nil, { description = "insert mode", group = "nvim command (insert)" }},
        { {}, "o", nil, { description = "open below", group = "nvim command (insert)" }},
        { {}, "a", nil, { description = "append", group = "nvim command (insert)" }},
        { {}, ";", nil, { description = "repeat t/T/f/F", group = "nvim find" }},
        { {}, ",", nil, { description = "reverse t/T/f/F", group = "nvim find" }},
        { {}, "/", nil, { description = ". find", group = "nvim find" }},
        { {}, "zt", nil, { description = "scroll cursor to the top", group = "nvim scroll" }},
        { {}, "zz", nil, { description = "scroll cursor to the center", group = "nvim scroll" }},
        { {}, "zb", nil, { description = "scroll cursor to the bottom", group = "nvim scroll" }},
        { { "Alt" }, "e", nil, { description = "scroll line up", group = "nvim scroll" }},
        { { "Alt" }, "y", nil, { description = "scroll line down", group = "nvim scroll" }},
        { {}, ":", nil, { description = "enter command mode", group = "nvim misc" }},
        { {}, "?", nil, { description = "list shortcuts", group = "nvim misc" }},
        { {}, "t", nil, { description = "show clock", group = "nvim misc" }},
    }
}
appkeys["lf"] = {
    style = command,
    pack = {
        { {}, ".", nil, { description = "toggle hidden .files", group = "lf" }},
        { {}, "za", nil, { description = "info size:time", group = "lf" }},
        { {}, "zh", nil, { description = "hidden", group = "lf" }},
        { {}, "zn", nil, { description = "info", group = "lf" }},
        { {}, "zr", nil, { description = "reverse", group = "lf" }},
        { {}, "zs", nil, { description = "info size", group = "lf" }},
        { {}, "zt", nil, { description = "info time", group = "lf" }},
        { {}, "q", nil, { description = "quit", group = "lf" }},
        { {}, "k", nil, { description = "move with arrows", group = "lf" }},
        { {}, "y", nil, { description = "copy", group = "lf" }},
        { {}, "p", nil, { description = "paste", group = "lf" }},
        { {}, "c", nil, { description = "clear", group = "lf" }},
        { {}, "space", nil, { description = "select", group = "lf" }},
        { {}, "u", nil, { description = "unselect", group = "lf" }},
        { {}, "v", nil, { description = "invert", group = "lf" }},
        { {}, "r", nil, { description = "rename", group = "lf" }},
        { {}, "f", nil, { description = "find", group = "lf" }},
        { {}, "F", nil, { description = "find back", group = "lf" }},
        { {}, ";", nil, { description = "find next", group = "lf" }},
        { {}, ",", nil, { description = "find prev", group = "lf" }},
        { {}, "h", nil, { description = "updir", group = "lf" }},
        { {}, "l", nil, { description = "open", group = "lf" }},
        { {}, "gh", nil, { description = "cd", group = "lf" }},
        { {}, "gg", nil, { description = "top", group = "lf" }},
        { {}, "G", nil, { description = "bootm", group = "lf" }},
        { {}, ":", nil, { description = "read", group = "lf" }},
        { {}, "$", nil, { description = "shell", group = "lf" }},
        { {}, "%", nil, { description = "shell pipe", group = "lf" }},
        { {}, "!", nil, { description = "shell wait", group = "lf" }},
        { {}, "&amp;", nil, { description = "shell async", group = "lf" }},
        { {}, "/", nil, { description = "search", group = "lf" }},
        { {}, "?", nil, { description = "search back", group = "lf" }},
        { {}, "N", nil, { description = "search prev", group = "lf" }},
        { {}, "n", nil, { description = "search next", group = "lf" }},
        { {}, "m", nil, { description = "mark save", group = "lf" }},
        { {}, "'", nil, { description = "mark load", group = "lf" }},
        { {}, '"', nil, { description = "mark remove", group = "lf" }},
        { {}, "t", nil, { description = "tag toggle", group = "lf" }},
        { {"Ctrl"}, "j", nil, { description = "enter", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "c", nil, { description = "interrupt", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "n", nil, { description = "history next", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "p", nil, { description = "history prev", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "b", nil, { description = "Left", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "f", nil, { description = "Right", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "e", nil, { description = "end", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "a", nil, { description = "home", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "u", nil, { description = "delete home", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "d", nil, { description = "delete", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "k", nil, { description = "delete end", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "w", nil, { description = "delete word", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "y", nil, { description = "yank", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "t", nil, { description = "transpose", group = "lf Ctrl cmd" }},
        { {"Ctrl"}, "r", nil, { description = "reload", group = "lf Ctrl cmd" }},
        { { "Alt" }, "u", nil, { description = "uppercase-word", group = "lf Alt cmd" }},
        { { "Alt" }, "l", nil, { description = "lowercase-word", group = "lf Alt cmd" }},
        { { "Alt" }, "t", nil, { description = "transpose word", group = "lf Alt cmd" }},
        { { "Alt" }, "f", nil, { description = "word", group = "lf Alt cmd" }},
        { { "Alt" }, "b", nil, { description = "word back", group = "lf Alt cmd" }},
        { { "Alt" }, "d", nil, { description = "delete word", group = "lf Alt cmd" }},
        { { "Alt" }, "c", nil, { description = "capitalize word", group = "lf Alt cmd" }},
    }
}
appkeys["mpv"] = {
    style = { column = 2, geometry = { width = 3600, height = 920 } },
    pack = {
        {{}, "f", nil,{ description = "Toggle fullscreen", group = "General" }},
        {{}, "s", nil,{ description = "Take a screenshot", group = "General" }},
        {{ "Shift" }, "s", nil,{ description = "Take a screenshot without subtitles", group = "General" }},
        {{}, "q", nil,{ description = "Quit", group = "General" }},
        {{ "Shift" }, "q", nil,{ description = "Quit saving current position", group = "General" }},
        {{}, "o", nil,{ description = "Show progress", group = "General" }},
        {{ "Shift" }, "o", nil,{ description = "Toggle show progress", group = "General" }},
        {{}, "F9", nil,{ description = "Show the list of audio and subtitle", group = "General" }},
        {{"Shift"}, "a", nil,{ description = "Cycle aspect ratio", group = "General" }},
        {{}, "F8", nil,{ description = "Show the playlist", group = "Playlist" }},
        {{ "Shift" }, ",", nil,{ description = "Forward in playlist", group = "Playlist" }},
        {{ "Shift" }, ".", nil,{ description = "Backward in playlist", group = "Playlist" }},
        {{}, "Space", nil,{ description = "Play/pause", group = "Playback" }},
        {{}, "[", nil,{ description = "Decrease speed", group = "Playback" }},
        {{}, "]", nil,{ description = "Increase speed", group = "Playback" }},
        {{}, "{", nil,{ description = "Halve current speed", group = "Playback" }},
        {{}, "}", nil,{ description = "Double current speed", group = "Playback" }},
        {{}, "l", nil,{ description = "Set/clear A-B loop points", group = "Playback" }},
        {{ "Shift" }, "l", nil,{ description = "Toggle infinite looping", group = "Playback" }},
        {{}, "Backspace", nil,{ description = "Reset speed to normal", group = "Playback" }},
        {{}, "m", nil,{ description = "Mute/unmute", group = "Audio" }},
        {{ "Control" }, "-", nil,{ description = "Decrease audio delay", group = "Audio" }},
        {{ "Control" }, "+", nil,{ description = "Increase audio delay", group = "Audio" }},
        {{}, "#", nil,{ description = "Cycle through audio tracks", group = "Audio" }},
        {{}, "PageUp", nil,{ description = "Next chapter", group = "Navigation" }},
        {{}, "PageDn", nil,{ description = "Previous chapter", group = "Navigation" }},
        {{}, ",", nil,{ description = "Previous frame", group = "Navigation" }},
        {{}, ".", nil,{ description = "Next frame", group = "Navigation" }},
        {{}, "Right", nil,{ description = "Forward 5 seconds", group = "Navigation" }},
        {{}, "Left", nil,{ description = "Backward 5 seconds", group = "Navigation" }},
        {{}, "Up", nil,{ description = "Forward 60 seconds", group = "Navigation" }},
        {{}, "Down", nil,{ description = "Backward 60 seconds", group = "Navigation" }},
        {{ "Control" }, "Left", nil,{ description = "Seek to the previous subtitle", group = "Navigation" }},
        {{ "Control" }, "Right", nil,{ description = "Seek to the next subtitle", group = "Navigation" }},
        {{ "Shift" }, "Backspace", nil,{ description = "Undo  the  last  seek", group = "Navigation" }},
        {{ "Control", "Shift" }, "Backspace", nil,{ description = "Mark the current position", group = "Navigation" }},
        {{}, "v", nil,{ description = "Show/hide subtitles", group = "Subtitles" }},
        {{}, "j", nil,{ description = "Next subtitle", group = "Subtitles" }},
        {{ "Shift" }, "j", nil,{ description = "Previous subtitle", group = "Subtitles" }},
        {{}, "z", nil,{ description = "Increase subtitle delay", group = "Subtitles" }},
        {{}, "x", nil,{ description = "Decrease subtitle delay", group = "Subtitles" }},
        {{}, "r", nil,{ description = "Move subtitles up", group = "Subtitles" }},
        {{}, "t", nil,{ description = "Move subtitles down", group = "Subtitles" }},
        {{}, "u", nil,{ description = "Style overrides on/off", group = "Subtitles" }},
        {{}, "1", nil,{ description = "Decrease contrast", group = "Video" }},
        {{}, "2", nil,{ description = "Increase contrast", group = "Video" }},
        {{}, "3", nil,{ description = "Decrease brightness", group = "Video" }},
        {{}, "4", nil,{ description = "Increase brightness", group = "Video" }},
        {{}, "5", nil,{ description = "Decrease gamma", group = "Video" }},
        {{}, "6", nil,{ description = "Increase gamma", group = "Video" }},
        {{}, "7", nil,{ description = "Decrease saturation", group = "Video" }},
        {{}, "8", nil,{ description = "Increase saturation", group = "Video" }},
        {{}, "w", nil,{ description = "Decrease pan-and-scan range", group = "Zoom" }},
        {{}, "e", nil,{ description = "Increase pan-and-scan range", group = "Zoom" }},
        {{ "Alt" }, "-", nil,{ description = "Decrease zoom", group = "Zoom" }},
        {{ "Alt" }, "+", nil,{ description = "Increase zoom", group = "Zoom" }},
        {{ "Alt" }, "Backspace", nil,{ description = "Reset zoom", group = "Zoom" }},
        {{ "Alt" }, "Arrow", nil,{ description = "Move the video rectangle", group = "Zoom" }},
        {{ "Shift" }, "s", nil,{ description = "Cut start", group = "Cut script" }},
        {{ "Shift" }, "e", nil,{ description = "Cut end", group = "Cut script" }},
        {{ "Shift" }, "c", nil,{ description = "Change cut encoding", group = "Cut script" }},
        {{ }, "c", nil,{ description = "Cut file", group = "Cut script" }},
    }
}
appkeys["firefox"] = {
    style = { column = 2, geometry = { width = 450, height = 350 } },
    pack = {
        {{"Alt"}, "1..9", nil,{ description = "Go to tab", group = "Tabs" }},
        {{ "Control" }, "t", nil,{ description = "New tab", group = "Tabs" }},
        {{ "Control" }, "w", nil,{ description = "Close tab", group = "Tabs" }},
        {{ "Control" }, "Tab", nil,{ description = "Next tab", group = "Tabs" }},
        {{ "Control", "Shift" }, "Tab", nil,{ description = "Previous tab", group = "Tabs" }},
    }
}
appkeys["code"] = {
    style = { column = 2, geometry = { width = 450, height = 350 } },
    pack = {
        {{}, "F1", nil, { description = "Commands", group = "Tabs" }},
        {{"Ctrl"}, "x", nil, { description = "Cut line", group = "Editing" }},
        {{"Ctrl"}, "c", nil, { description = "Copy line", group = "Editing" }},
        {{"Ctrl"}, "v", nil, { description = "Paste line", group = "Editing" }},
        {{"Ctrl"}, "z", nil, { description = "Undo", group = "Editing" }},
        {{"Ctrl", "Shift"}, "z", nil, { description = "Redo", group = "Editing" }},
        {{"Ctrl"}, "s", nil, { description = "Save file", group = "Editing" }},
        {{"Ctrl"}, "f", nil, { description = "Find", group = "Editing" }},
        {{"Ctrl"}, "h", nil, { description = "Replace", group = "Editing" }},
        {{"Ctrl"}, "g", nil, { description = "Go to line", group = "Editing" }},
        {{"Ctrl", "Shift"}, "f", nil, { description = "Find in files", group = "Editing" }},
        {{"Ctrl"}, "/", nil, { description = "Toggle line comment", group = "Editing" }},
        {{"Ctrl"}, "d", nil, { description = "Select next occurrence", group = "Editing" }},
        {{"Ctrl", "Shift"}, "l", nil, { description = "Select all occurrences", group = "Editing" }},
        {{"Ctrl"}, "Enter", nil, { description = "Insert line below", group = "Editing" }},
        {{"Ctrl", "Shift"}, "Enter", nil, { description = "Insert line above", group = "Editing" }},
        {{"Ctrl", "Shift"}, "k", nil, { description = "Delete line", group = "Editing" }},
        {{"Alt"}, "Up", nil, { description = "Move line up", group = "Editing" }},
        {{"Alt"}, "Down", nil, { description = "Move line down", group = "Editing" }},
        {{"Shift", "Alt"}, "Down", nil, { description = "Copy line down", group = "Editing" }},
        {{"Shift", "Alt"}, "Up", nil, { description = "Copy line up", group = "Editing" }},
        {{"Ctrl", "Shift"}, ":", nil, { description = "Jump to matching bracket", group = "Editing" }},
        {{"Ctrl"}, "p", nil, { description = "Quick open file", group = "Editing" }},
        {{"Ctrl"}, "Tab", nil, { description = "Switch between open files", group = "Editing" }},
        {{"Ctrl"}, "b", nil, { description = "Toggle sidebar", group = "Editing" }},
        {{"Ctrl", "Shift"}, "e", nil, { description = "Show Explorer sidebar", group = "Editing" }},
        {{"Ctrl", "Shift"}, "f", nil, { description = "Show Search sidebar", group = "Editing" }},
        {{"Ctrl", "Shift"}, "g", nil, { description = "Show Source Control sidebar", group = "Editing" }},
        {{"Ctrl", "Shift"}, "d", nil, { description = "Show Debug sidebar", group = "Editing" }},
        {{"Ctrl", "Shift"}, "x", nil, { description = "Show Extensions sidebar", group = "Editing" }},
    }
}
return appkeys
